name: app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  amazon_cognito_identity_dart_2: ^0.1.25+4
  auto_size_text: ^2.1.0
  built_value: ^7.1.0
  cached_network_image: null
  chopper: ^3.0.6
  connectivity: ^3.0.6
  country_code_picker: ^2.0.2
  cupertino_icons: ^1.0.2
  flick_video_player: ^0.3.1
  flutter:
    sdk: flutter
  flutter_absolute_path: ^1.0.6
  flutter_better_camera: null
  flutter_ffmpeg: ^0.4.2
  flutter_icons: ^1.1.0
  flutter_phoenix: ^1.0.0
  flutter_secure_storage: ^4.2.0
  flutter_staggered_grid_view: ^0.4.0
  fluttertoast: ^8.0.7
  image_cropper: ^1.4.1
  image_picker: ^0.8.2
  intl: ^0.17.0
  logger: ^1.0.0
  multi_image_picker2: ^5.0.2
  path_provider: null
  provider: ^5.0.0
  shimmer: ^2.0.0
  sms_autofill: ^2.0.0
  uuid: 
  video_player: ^2.1.12
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^1.10.11

  built_value_generator: 7.1.0

  chopper_generator: ^3.0.6

  flutter_test:
    sdk: flutter

  import_sorter: 4.3.0

  lint: ^1.5.3

dependency_overrides:
  analyzer: 0.41.1

  dart_style: 1.3.13

  yaml: 3.1.0

  http: 0.12.0

flutter:
  uses-material-design: true

  assets:
    - config/
    - assets/images/
