name: app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  amazon_cognito_identity_dart_2: ^1.0.0

  auto_size_text: ^3.0.0

  built_value: ^8.0.0

  connectivity: ^3.0.6

  country_code_picker: ^2.0.2

  chopper: ^4.0.0

  cupertino_icons: ^1.0.2

  image_cropper: ^1.4.1

  image_picker: ^0.8.2

  intl: ^0.17.0

  logger: ^1.0.0

  provider: ^6.0.0

  flutter:
    sdk: flutter

  flutter_ffmpeg: ^0.4.2

  fluttericon: ^2.0.0        

  flutter_secure_storage: ^5.0.0

  flutter_staggered_grid_view: ^0.4.0

  fluttertoast: ^8.0.7

  flutter_phoenix: ^1.0.0

  sms_autofill: ^2.0.0

  yaml: ^3.1.0

  flutter_better_camera: ^1.0.0

  multi_image_picker2: ^5.0.2

  path_provider: ^2.0.0

  video_player: ^2.1.12

  exif: ^3.0.0

dev_dependencies:
  build_runner: ^2.0.0

  built_value_generator: ^8.0.0

  chopper_generator: ^4.0.0

  flutter_test:
    sdk: flutter

  import_sorter: ^4.6.0

  lint: ^1.5.3

# dependency_overrides:
  

flutter:
  uses-material-design: true

  assets:
    - config/
    - assets/images/
